version: '2'

services:
    web:
        # build: .
        image: aparticula/omeka
        container_name: omeka_web
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/vhost.conf:/etc/nginx/conf.d/default.conf
            - ./conf/php.ini:/etc/php/7.0/fpm/conf.d/30-custom.ini
            - ./omeka-src:/app
            - ./conf/omeka/htaccess.dummy:/app/.htaccess
            - ./conf/omeka/db.ini:/app/db.ini
            - ./conf/omeka/config.ini:/app/application/config/config.ini
            # - ./plugins/MyPlugin:/app/plugins/MyPlugin
            # - ./themes/my-theme:/app/themes/my-theme
        ports:
            - "8088:80"
        links:
            - db:db

    db:
        image: soifou/mariadb-alpine
        container_name: omeka_db
        # volumes:
        #     - /var/lib/boot2docker/omekadb:/data/db/mysql
        environment:
            - DB_USER=root
            - DB_PASS=root
